POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
    "author": "Maria",
    "url": "www.flower.com",
    "title": "Spring is Here OR NOT",
    "likes": 2
}

###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "selina@zheng.com",
    "name": "Selina Zheng",
    "password": "password"
}
