POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
    "author": "Maria",
    "url": "www.flower.com",
    "title": "Spring is Here OR NOT",
    "likes": 2
}

###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "mark@twain.com",
    "name": "Mark Twain",
    "password": "password"
}

###
POST http://localhost:3001/api/readinglists HTTP/1.1
Content-Type: application/json

{
    "userId": 2,
    "blogId": 7
}
